tech_jokes = [
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why was the JavaScript developer sad? Because he didn't 'null' his ex.",
    "How do you comfort a JavaScript bug? You 'console' it.",
    "Why don’t programmers like nature? It has too many bugs.",
    "Why did the developer go broke? Because he used up all his cache.",
    "Why was the computer cold? It left its Windows open.",
    "Why do Java developers wear glasses? Because they don’t see sharp.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "What’s a programmer’s favorite place to hang out? The Foo Bar.",
    "Why do Python programmers prefer snakes? Because they love Pythonic code!",
    "Why did the function break up with the variable? It had too many arguments!",
    "Why do programmers hate camping? Because they hate debugging their tents!",
    "What did the server say to the client? You make too many requests!",
    "Why do developers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why was the computer cold? It left its Windows open!",
    "How does a programmer open a jar? They install Java first!",
    "Why do backend developers hate frontend developers? Because they make everything look easy!",
    "Why do programmers prefer iOS development? Because Android has too many fragments!",
    "What is a programmer’s favorite hangout place? The Stack Overflow cafe!",
    "Why don’t Java programmers need glasses? Because they can C#!",
    "Why was the JavaScript developer tired? Because he didn't 'await' his rest!",
    "Why did the database administrator break up with his girlfriend? Too many 'relations' to handle!",
    "Why do developers never play hide and seek? Because good coders never hide their bugs!",
    "Why do software engineers never lock their houses? Because they always leave a backdoor open!",
    "Why was the web developer always calm? Because he had a good 'framework'!",
    "Why did the Python programmer get rejected? Because he had too many 'self' issues!",
    "What’s a programmer’s favorite sport? Ping (without Pong)!",
    "Why was the CSS designer bad at relationships? Because he always had issues with alignment!",
    "What do JavaScript and politicians have in common? They both have lots of 'promises' but never resolve!",
    "Why was the function feeling sad? It was called too many times and had no 'return'!",
    "Why don’t programmers like to break up? Because they hate handling exceptions!",
    "Why do programmers prefer coffee over tea? Because Java is life!",
    "What did the developer say to the client? It works on my machine!",
    "Why do programmers prefer Linux? Because they like freedom (and suffering)!",
    "Why do developers always carry a notebook? To 'log' everything!",
    "Why did the programmer refuse to use a map? Because he preferred recursion!",
    "Why do data scientists love coffee? Because without caffeine, their models won’t 'learn'!",
    "Why did the HTML tag break up with the CSS file? It wanted more 'style'!",
    "Why did the developer get locked out of his house? He forgot his 'keys'!",
    "Why was the database slow? Too many joins in the party!",
    "Why do software engineers love horror movies? Because they enjoy debugging nightmares!",
    "Why did the JavaScript array go to therapy? Because it had too many issues with 'undefined'!",
    "Why do Python developers love simplicity? Because they like things 'indent'ed properly!",
    "Why was the programmer always single? Because he couldn’t handle 'commit'!",
    "Why did the laptop go to therapy? It had too many 'cores' issues!",
    "Why did the developer bring a ladder to work? Because he wanted to reach new 'heights' in coding!",
    "Why do AI engineers love jokes? Because they always have 'Neural' responses!",
    "Why do engineers love open-source projects? Because sharing is 'caring'!",
    "Why did the programmer always win at poker? Because he knew how to 'code' his way out!"
]
