[project]
name = "jokes-generators"
version = "0.1.0"
description = "ultimate joke generator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "streamlit>=1.43.1",
]
